export const GET_LFG_POSTS = 'GET_LFG_POSTS';
export const GET_LFG_POST = 'GET_LFG_POST';
export const CREATE_LFG_POST = 'CREATE_LFG_POST';
export const GET_PLAYER_CHARACTERS = 'GET_PLAYER_CHARACTERS';
export const GET_MATCHING_USERS = 'GET_MATCHING_USERS';
export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const CREATE_POST_START = 'CREATE_POST_START';
export const DELETE_LFG_POST =  'DELETE_LFG_POST';
export const SHOW_ALL_POSTS = 'SHOW_ALL_POSTS';
export const FILTER_MODE = 'FILTER_MODE';
export const FILTER_LOOKING_FOR = 'FILTER_LOOKING_FOR';
export const FILTER_MIC = 'FILTER_MIC';
export const FILTER_ELO = 'FILTER_ELO';
export const FILTER_KD = 'FILTER_KD';
export const SET_ERRORS = 'SET_ERRORS';
export const SET_FETCH_POST_ERRORS = 'SET_FETCH_POST_ERRORS';
export const FETCH_FIRETEAM_START = 'FETCH_FIRETEAM_START';
export const FETCH_FIRETEAM_END = 'FETCH_FIRETEAM_END';
export const SET_FIRETEAM_ERRORS = 'SET_FIRETEAM_ERRORS';
export const FETCH_PLAYER_DATA = 'FETCH_PLAYER_DATA';
export const SET_USER_ERRORS = 'SET_USER_ERRORS';
export const FETCH_PLAYER_START = 'FETCH_PLAYER_START';
export const FETCH_PLAYER_END = 'FETCH_PLAYER_END';
export const SET_PLAYER_ERRORS = ' SET_PLAYER_ERRORS';




