export const GET_LFG_POSTS = 'GET_LFG_POSTS';
export const GET_LFG_POST = 'GET_LFG_POST';
export const CREATE_LFG_POST = 'CREATE_LFG_POST';
export const GET_PLAYER_CHARACTERS = 'GET_PLAYER_CHARACTERS';
export const GET_MATCHING_USERS = 'GET_MATCHING_USERS';

